import re
import streamlit as st

def replace(article, keys):
    """
    替换文章内容

    :param article: 文章内容
    :param keys: 用户输入的单词

    :return: 替换后的文章内容

    """
    def key(matched):
        return "**"+keys[int(matched.groups()[1])-1]+"**"
    return re.sub("(\{\{)([0-9])(\}\})", key, article)

def clear_text():
    st.session_state["text"] = ""

def play(article):
    # Init
    if "Input" not in st.session_state:
        st.session_state["Input"] = []

    # Input
    if len(st.session_state["Input"]) < len(article["hints"]):
        st.info("Hint: "+article["hints"][len(st.session_state["Input"])])
        col1, col2 = st.columns(2)
        with col1:
            text = st.text_input("Enter", key="text", placeholder="Please Enter:",label_visibility="collapsed")
            if text:
                st.session_state["Input"].append(text)
        with col2:
            st.button("Clear", on_click = clear_text)
    
    # Replace and display
    if len(st.session_state["Input"]) == len(article["hints"]):
        newart = replace(article["article"], st.session_state["Input"])
        st.caption("This is the article generated by your key words:")
        st.markdown("## "+article["title"]+"\n")
        st.markdown(newart)
